[package]
name = "signature"
version = "0.1.0"
edition = "2021"

[dependencies]
glob = "0.3.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.40.0", features = ["full"] }
